### ISSUE TITLE
Trouble understanding `hotel.room.reservation.line` and `hotel_reservation.line`

### ISSUE THREAD

**Issue by JayVora-SerpentCS** [OCA/vertical-hotel#106]
I’m getting to know the code, and have trouble understanding the difference between the models `hotel.room.reservation.line` and `hotel_reservation.line`.

from 
CoopIt easy
@mclaeysb

**Comment by vimalpatelserpentcs** [comment]
> I’m getting to know the code, and have trouble understanding the difference between the models `hotel.room.reservation.line` and `hotel_reservation.line`.
> 
> from
> CoopIt easy
> @mclaeysb

**1. hotel_reservation.line** : This model used in the hotel reservation, where you can select room category and based on that you can select a room ( Technically, this model is used in hotel.reservation as one2many(hotel_reservation.line))
Screenshot link: https://prnt.sc/tae8nt 

**2. hotel.room.reservation.line:** Generally, we can say as room reservation movement/history tables, In Reservation Summary (Dashboard) the values come from hotel.room.reservation.line model and folio.room.line model.
 (Technically, When we booked any room from reservation then that room booking record create into the hotel.room.reservation.line models and record update/delete accordingly)
Screenshot link: https://prnt.sc/taekgp
