### ISSUE TITLE
Calendar view Room summary

### ISSUE THREAD

**Issue by nch-odoo** [OCA/vertical-hotel#112]
hi, 
The calendar view for room summary shows 1 day free instead of reserved. for eg: 
I have these reservation 
![Selection_424](https://user-images.githubusercontent.com/7599820/87867690-43120100-c9ad-11ea-9729-b5f16361f7a4.jpg)
Now I run Reservation summary view it should show me RESERVED from 13th to 18th but It only shows from 13th to 17th

![Selection_425](https://user-images.githubusercontent.com/7599820/87867713-72287280-c9ad-11ea-86e8-56187b09ee34.jpg)

Looking at some details in the code I see some timezone issues. Because the above checkin and checkout will be stored as UTC so checkin will be as 08/12/2020 23:00:00 and checkout will be as 08/17/2020 23:00:00.
but the date range that is selected to fetch details are as under
2020-08-13 18:06:59
2020-08-14 18:06:59
2020-08-15 18:06:59
2020-08-16 18:06:59
2020-08-17 18:06:59
as per database record this last condition will fail. 
2020-08-18 18:06:59

Expected Result
It Should show RESERVED from 13th to 18th

Thanks

--

**Comment by nch-odoo** [comment]
@SerpentCS @pedrobaeza @robinkeunen

**Comment by SerpentCS** [comment]
Naresh,
Specify the version please.
Thanks.

**Comment by robinkeunen** [comment]
Hi @nch-odoo we need the version indeed. Plus I reimplemented the summary feature here https://github.com/OCA/vertical-hotel/pull/113 if you want to have a look.

**Comment by nch-odoo** [comment]
@SerpentCS the version 11 CE

**Comment by nch-odoo** [comment]
@robinkeunen @mclaeysb  I checked your updates and it also has same issue

**Comment by mclaeysb** [comment]
I'm not sure I understand your the technical explanation @nch-odoo but from what I understand the summary lists the nights that are still free. A guest arriving on the 13th and leaving on the 18th will not be staying the night of the 18th, and thus that box should say 'Free' (unless the departure is too late in the afternoon, then it should say 'Reserved' indeed).
