### ISSUE TITLE
Installing vertical-hotel in Odoo 9

### ISSUE THREAD

**Issue by adrian7818** [OCA/vertical-hotel#12]
Hi there,

I have tried to search for the steps to install the module into my Odoo 9.0.
Even after I have unpacked the zip file in addons folder. And enable the Developer Mode, I'm still unable to see the module available in my Odoo App list.

Is there something which I might have missed out here?
Thank you.

**Comment by elicoidal** [comment]
Hi @adrian7818 
thanks for your interest in the OCA modules.
Those modules are not installable in v9 (only v7) because they have not yet been migrated.
If you are interested in working in their migration let us know as we are looking for volunteers.
I close the issue accordingly
