### ISSUE TITLE
[v10]Reservation booking issues and reservation lines

### ISSUE THREAD

**Issue by kawan2882** [OCA/vertical-hotel#127]
Halo There i have a an issue with your module Hotel Booking Management

where when i book there is a message like this

""You tried to Confirm reservation with room those already reserved in this Reservation Period. Overlap Dates are""
![image](https://user-images.githubusercontent.com/72402654/95100647-8a618f80-075b-11eb-8767-15b4a363d65f.png)

The problem is i dont have a room already book on that day..why this is happening??is there a bug in the module ? what it the solution?

i have also issue when booking reservation in the hotel room lines the list is duplicated to many times like this.

![error inserted many times(duplicated hundreds)](https://user-images.githubusercontent.com/72402654/95100788-a5cc9a80-075b-11eb-932f-3bb249ddcd24.jpg)

Kindly your solution about this matter

Thank You

Kawan

**Comment by drvaya** [comment]
Yes I am also facing same issue - especially when doing multiple room booking in single reservation for a guest.

Any solutions available for this ?

**Comment by SerpentCS** [comment]
@vimalpatelserpentcs Please take a look.

**Comment by vimalpatelserpentcs** [comment]
Hello @drvaya @kawan2882 , On which version have you facing this issue ?

**Comment by drvaya** [comment]
I faced this with v10.0

**Comment by drvaya** [comment]
@vimalpatelserpentcs - Any updates on this issue ? Can you confirm if this is reproducible on any higher versions of Odoo then we would have to work out an upgrade in that case.

**Comment by Rajan-SerpentCS** [comment]
Hello @drvaya,
I have checked and not Facing such kind of issue in version 14.0.
