### ISSUE TITLE
Problem when create new Room Type

### ISSUE THREAD

**Issue by luismata01** [OCA/vertical-hotel#131]
When I try to create a new Room Type de Category field need create an edit a new and open a new window with the same requirements and never stop.

**Comment by JayVora-SerpentCS** [comment]
@luismata01 would you please share a video of this? or may be on runbot?
Thanks

**Comment by luismata01** [comment]
Hi @JayVora-SerpentCS 

This is the video [https://drive.google.com/file/d/1E5pdcrFN-fB1z_kuGllYJR9lOlSAWxpx/view?usp=sharing](url)

**Comment by luismata01** [comment]
How can I load the Demo data from xml?

[https://github.com/OCA/vertical-hotel/blob/13.0/hotel/demo/hotel_data.xml](url)}}

Can you help me please?

**Comment by JayVora-SerpentCS** [comment]
@luismata01 We couldn't access the video as it needs permission.
Loading demo data is an odoo feature when you load the database with DEMO options checked yes.
@dhruvitaSerpentCS can you check for the said issue?
Thanks.
