### ISSUE TITLE
Problem with food item configuration

### ISSUE THREAD

**Issue by pareeshi** [OCA/vertical-hotel#133]
Hi,

I was using the hotel restaurant management model, but i have problem during food item and type configuration.
I report you the screenshot, in which there's no "Add" button.
Anyone can help me about this? 

Thanks for atttention,
Have a good day!

(i am using Odoo 12.0 with the same version of the module, on Windows 10)

![Schermata 2021-01-04 alle 12 41 55](https://user-images.githubusercontent.com/28765756/103531931-91975700-4e8a-11eb-9d2e-481eb2364c0d.png)
![Schermata 2021-01-04 alle 12 42 00](https://user-images.githubusercontent.com/28765756/103531934-922fed80-4e8a-11eb-8339-eb7234d655b1.png)

**Comment by Rajan-SerpentCS** [comment]
@pareeshi 
Fixed issue in 12.0 branch please take the latest code and check it.

cc @JayVora-SerpentCS

**Comment by pareeshi** [comment]
Perfect! It works now!
Thanks a lot
