### ISSUE TITLE
Error "Room Duplicate Exceeded!, You Cannot Take Same Doble - 103 Room Twice!" In Folio Create Odoo 13

### ISSUE THREAD

**Issue by jwcaceres78** [OCA/vertical-hotel#137]
I reserver Two rooms:
![image](https://user-images.githubusercontent.com/74755273/116838118-d3af7b80-ab92-11eb-9b25-9a60c0be6ade.png)

But when I want to create the Service detail I have this message
![image](https://user-images.githubusercontent.com/74755273/116838164-078aa100-ab93-11eb-96d9-36134be9fe20.png)

Can you helpme?

Thanks Regards,
Jorge

**Comment by JayVora-SerpentCS** [comment]
@vimalpatelserpentcs Please check.
Thanks

**Comment by vimalpatelserpentcs** [comment]
@jwcaceres78, Fixed this issue and added PR #139  for it.
cc @JayVora-SerpentCS
