### ISSUE TITLE
Error navigating menu

### ISSUE THREAD

**Issue by Matt-OBell** [OCA/vertical-hotel#14]
In v10, when I navigate from a menu to another eg 
a) when I click on Reservation, I get the error "TypeError: this.widget.active_view is null"
b) when I try to click on the hotel apps from the apps dashboard, I get the error "TypeError: obj is not a constructor"

Regards
Dare

**Comment by JayVora-SerpentCS** [comment]
Dare, this doesn't happen with latest version. Closing henceforth.
