### ISSUE TITLE
CE_12 | Hotel Folio Report Timezone Problem

### ISSUE THREAD

**Issue by sound675** [OCA/vertical-hotel#149]
Hi, I am using Odoo CE 12

I have installed Module:
- hotel
- hotel_reservation
- report_hotel_reservation

I have set the correct timezone for:
- My User
- The Contacts
- Working Hours

Then I have restart Odoo server, just to make sure

Problem :
Whenever I print "Hotel Folio Report", the Checkin and Checkout time printed on PDF is different with the Checkin and Checkout 
 time stated on Folio.
 But when I print "Hotel Reservation Report", all the Checkin and Checkout time are correct.
 
 What setting am I missing?
 
 Thank you for your time.

**Comment by JayVora-SerpentCS** [comment]
@vimalpatelserpentcs

**Comment by sound675** [comment]
Dear Rajan-SerpentCS

I hav seen that this issues has been fixed in 
https://github.com/OCA/vertical-hotel/pull/155

Thank you for your fix.

However I am using Odoo CE ver 12.
But the fix is only for version 14 ?

Please advice.

Thank you

**Comment by JayVora-SerpentCS** [comment]
@Rajan-SerpentCS please backport upon convenience.

**Comment by sound675** [comment]
I thank you for your kindness!
 
I am a very newbie to Odoo and I install Odoo CE ver 12 in Windows
Really hoping for your feedback Mr. JayVora and Mr. Rajan

Thank you very much
