### ISSUE TITLE
Computed fields not updating in the UI

### ISSUE THREAD

**Issue by bguernouti** [OCA/vertical-hotel#150]
Since the inheritance method of the `sale.order` and `sale.order.line` models is a delegate inheritance, the fields like `amount_untaxed`, `amount_tax`, `amount_total` in the model `hotel.folio` (`sale.order`)
and fields `price_subtotal`, `price_total` in the model `hotel.folio.line` (`sale.order.line`) are not live updated in the folio creation form.

I discovered that we have to re-implement the decorated methods defined in the parent models `sale.order` `sale.order.line` inside every new model `hotel.folio` `hotel.folio.line`  with all their corresponding fields (fields that have **compute='<method_name>'**)

**Comment by JayVora-SerpentCS** [comment]
@vimalpatelserpentcs can you take a look?
Thanks.
