### ISSUE TITLE
Question regarding PMS repositories

### ISSUE THREAD

**Issue by flotho** [OCA/vertical-hotel#153]
Hi,

I would like to thanks both maintainer of this repo and the OCA/pms ones, we have great modules there.
I'm wondering if there on't be a way to share some features like reservation, room/property descriptions etc...
What's your point of view on this?

Regards

**Comment by JayVora-SerpentCS** [comment]
True, agreed! 
Do we have a list of features planned?
Thanks,

**Comment by pedrobaeza** [comment]
cc @DarioLodeiros

**Comment by flotho** [comment]
Another way of sharing could be with https://github.com/OCA/vertical-realestate

What I can imagine is to first start by adding more descriptions to the properties / room / estate :
* precise location with a link to partner (to get country, department, direct geomaps, etc)
* more information regarding the surface of the (room preperties)
* Number of pieces, number of floor
* Which floor etc..
* Photos, videos
* .../...

Those information would be helpful for those 3 repo to locate the properties/room/estates and descibe in a more complete way the product. Default values in location or in pieces number would be easy to do so that not so much set up would be added
Maybe it would be possible to display this in the portal in the end, or on the shop part ;-)

I currently waiting for an answer from a customer to start with pms and they asked me many of thoses field. As your v14 hotel module has just started, if you're Ok with this  @JayVora-SerpentCS @DarioLodeiros  I'll try to improve/share/merge the concept of property/room/(estate).
If you're Ok, please tell me what will be the best place to do this ?
* another repo 
* in pms and referencing it from vertical-hotel

Thanks in advance for sharing your feedback.

Regards

**Comment by DarioLodeiros** [comment]
Hi!
Thanks cc @pedrobaeza!!
Pms project work with multicompany context, and we dev a property model to manage a multiproperty security rules etc...
I think that pms and verticalhotel has a core differents, We could propose an integration study of both repositories for future versions, v15 or later.
The pms road map has an ambitious roadmap that include website booking, precheckins etc.. but by the momment we has the core in alpha dev status.
The pms repository is delighted with new contributions, taking into account the status, it would be advisable to open an issue with the proposal to confirm compatibility and needs.  We will help in any way possible :)
Thanks!

**Comment by pedrobaeza** [comment]
Darío, what Florent is proposing is to extract the base "property" model to a common module (`base_property`?), to be used by both verticals as core model data as a first step.

**Comment by DarioLodeiros** [comment]
Yes, I think that is a good first step, all right for me.
I even think that this module could be valid for other types of sectors
that need to segment the company into more specific units.

**Comment by pedrobaeza** [comment]
OK, then I think any of you can put the data model for seeing the shared fields.

**Comment by JayVora-SerpentCS** [comment]
There are thin line differences between Real estate, Property, Rental concept and Hotel.
Our concept would work for even : Community Clubs, sports clubs!

@flotho Can we have one shared sheet where we all share common data models?
So we can conclude there and later bring it to OCA. 
Just a thought.
Thanks.

**Comment by DarioLodeiros** [comment]
+1El 29 jul. 2021 13:31, "Serpent Consulting Services Pvt. Ltd." ***@***.***> escribió:
There are thin line differences between Real estate, Property, Rental concept and Hotel.
Our concept would work for even : Community Clubs, sports clubs!
@flotho Can we have one shared sheet where we all share common data models?
So we can conclude there and later bring it to OCA.
Just a thought.
Thanks.

**Comment by flotho** [comment]
> There are thin line differences between Real estate, Property, Rental concept and Hotel.
> Our concept would work for even : Community Clubs, sports clubs!

Great
> @flotho Can we have one shared sheet where we all share common data models?
> So we can conclude there and later bring it to OCA.

what are the OCA recommandations ?
prepare a furture merge request in this repo, start with a issue and checkbox, online excel file on any cloud? youyr advices will be followed.

Regards
