### ISSUE TITLE
Failed to render template : 'odoo.api.hotel.reservation object' has no attribute 'warehouse_id'

### ISSUE THREAD

**Issue by caster082** [OCA/vertical-hotel#169]

**Comment by fits-bandung** [comment]
Added error information that I found,
A warning appears when sending an email to a customer or when clicking the Send Reservation Email button.

The following warning appears,
Failed to render template : 'odoo.api.hotel.reservation object' has no attribute 'warehouse_id'
![image](https://user-images.githubusercontent.com/20293146/204497911-c71c2395-c235-43bd-afca-e0ae3755b2dd.png)

How to handle that problem?

**Comment by JayVora-SerpentCS** [comment]
Looks like an unmapped field being used on email.

which odoo version are you using ?

@shwetaserpentcs please check.

**Comment by fits-bandung** [comment]
This happened in Odoo version 14 CE with addons version 14 as well

**Comment by Amikre** [comment]
Same issue happens to me too. and I can't see the total unless I click Create folio, but when you create folio, you can't delete reservation if client cancels. so im left with a reserved room that can't be available anymore.

**Comment by ShwetaSerpentCS** [comment]
@andhi1 @Amikre I will check and update you.
