### ISSUE TITLE
Error when entering the reservation module with a different company than the first company in Odoo

### ISSUE THREAD

**Issue by totoday72** [OCA/vertical-hotel#172]
at the time of wanting to enter the reservations module through another company other Different hotel companies in a if it works but in the second one gives error and does not allow to enter the module.

## Module
hotel_reservation

## Describe the bug
When try enter to the hotel_reservation module with 2nd company, the message appears: 

The requested operation ("read" in "product" (product.product)) was rejected by any of the following rules:
(Records: [69] false (id = 36), user: user (id = 2))
Implicitly accessed through 'product' (product.product).

I try in other odoo 13 instance, and appear same error.

Note: this error only appears in hotel_reservation module, hotel module work normally

## To Reproduce
**Odoo 13**:

1. Create 2nd company ( example we have 2 hotels)
2. Set User to de 2nd company
3. Login User
4. Enter to hotel_reservation module

**Expected behavior**
When I perform the previous actions I hope that the module of the screen again with all the rooms for this empty hotel because they are different rooms for each of the hotels. and make the reservations for each one.

**Additional context**
Odoo Local
Ubuntu 18.04
16GB RAM

**Comment by totoday72** [comment]
> at the time of wanting to enter the reservations module through another company other Different hotel companies in a if it works but in the second one gives error and does not allow to enter the module.
> ## Module
> 
> hotel_reservation
> ## Describe the bug
> 
> When try enter to the hotel_reservation module with 2nd company, the message appears:
> 
> The requested operation ("read" in "product" (product.product)) was rejected by any of the following rules: (Records: [69] false (id = 36), user: user (id = 2)) Implicitly accessed through 'product' (product.product).
> 
> I try in other odoo 13 instance, and appear same error.
> 
> Note: this error only appears in hotel_reservation module, hotel module work normally
> ## To Reproduce
> 
> **Odoo 13**:
> 
> Steps to reproduce the behavior:
> 
>     1. Create 2nd company ( example we have 2 hotels)
> 
>     2. Set User to de 2nd company
> 
>     3. Login User
> 
>     4. Enter to hotel_reservation module
> 
> 
> **Expected behavior** When I perform the previous actions I hope that the module of the screen again with all the rooms for this empty hotel because they are different rooms for each of the hotels. and make the reservations for each one.
> 
> **Additional context** Odoo Local Ubuntu 18.04 16GB RAM

**Solution**
I create "Record Rules" for models.
- Hotel Service -> Domain: ['|',('company_id','=',False),('company_id', 'in', company_ids)]
- Hotel Room -> Domain: ['|',('company_id','=',False),('company_id', 'in', company_ids)]
- Hotel Amenities -> Domain: ['|',('company_id','=',False),('company_id', 'in', company_ids)]
- Hotel Reservation -> Domain: ['|',('warehouse_id.company_id','=',False),('warehouse_id.company_id', 'in', company_ids)]

All record rules are Global (no Group).

Greetings!

**Comment by JayVora-SerpentCS** [comment]
@nikul-serpentcs Can you help this be checked by @ShwetaSerpentCS once ?
Thanks.

**Comment by nikul-serpentcs** [comment]
Yes Sure @JayVora-SerpentCS
