### ISSUE TITLE
cannot see the icon

### ISSUE THREAD

**Issue by fgarcia-humanoide** [OCA/vertical-hotel#181]
cannot see the icon

## Module
vertical hotel app

## Describe the bug
cannot see the icon

## To Reproduce
14

1.
2.
3.

**Expected behavior**
a beautiful icon
![hotelnoseve](https://user-images.githubusercontent.com/7599709/203599997-71168b12-c927-48b4-aa9e-8a561205cea1.JPG)

**Additional context**
Add any other context about the problem here. (e.g. OS, Python version, ...)

**Comment by JayVora-SerpentCS** [comment]
@ShwetaSerpentCS pls see
