### ISSUE TITLE
Hotel room summary not showing draft state branch 14

### ISSUE THREAD

**Issue by typecookie** [OCA/vertical-hotel#183]
## Module
hotel_reservation in 14

## Describe the bug
In the hotel reservation Module and the reservation summary view when you make a reservation the draft state is not set in the summary table. so the blue color of a reserved room is not set in the view.

## To Reproduce
version 14

1. in Hotel Management click Reservations click  reservation summary
2. click a green free cell in the table
3. fill in data on the reservation popup click save
4. no change on table
5. if you confirm the reservation it will make a red cell on the table

**Expected behavior**
A blue cell with reserved should show up in step 4

**Additional context**
odoo from OCA branch 14
veritcal-hotel from OCA branch 14

**Comment by Amikre** [comment]
I have the same issue, when you create a folio for a reservation, the reservation turns red and you can't cancel it.
And without creating a folio you can't see the total price.
I created a reservation and then tried to see the total to pay, to do that you have to create a folio, by creating a folio you change the status of reservation from confirmed to done. and when you try to delete it, it says:
Sorry, you can only delete the reservation when it's draft!

**Comment by JayVora-SerpentCS** [comment]
@shwetaserpentcs
