### ISSUE TITLE
Reservation to Folio - Smartbutton

### ISSUE THREAD

**Issue by JayVora-SerpentCS** [OCA/vertical-hotel#19]
There is an O2M now, we should add a smartbutton to go to folio from Reservation(s).

**Comment by KrishnaPrajapati-SerpentCS** [comment]
Fix this issue : https://github.com/OCA/vertical-hotel/pull/26/commits/2050967b9f0a4cfde2168be0c02c44bfa6e6d71f

**Comment by JayVora-SerpentCS** [comment]
Thanks,
