### ISSUE TITLE
[7.0] You can not validate a field Folio for lack of currency

### ISSUE THREAD

**Issue by syci** [OCA/vertical-hotel#2]
![picture651-1](https://cloud.githubusercontent.com/assets/7081394/6391921/490b6fbc-bdb3-11e4-8f87-882784ca2466.png)

As shown in the attached picture , the currency field is not used to validate the record

**Comment by pedrobaeza** [comment]
Mario, please put your issue in english, as this one is not in spanish domain.

**Comment by JayVora-SerpentCS** [comment]
It has been corrected in v10. Do reopen if the issue is found.
