### ISSUE TITLE
[10] vertical-hottel -reservation  Error: QWeb2: Template 'summaryDetails' not found

### ISSUE THREAD

**Issue by bunhin** [OCA/vertical-hotel#30]
the error when click reservation summary:

Error: QWeb2: Template 'summaryDetails' not found

http://...../web/content/347-fb4e346/web.assets_common.js:2908
Traceback:
exception@http://...../web/content/347-fb4e346/web.assets_common.js:2908:7
_render@http://....../web/content/347-fb4e346/web.assets_common.js:2953:92
.....
....
fire@http://.../web/content/347-fb4e346/web.assets_common.js:541:281
fireWith@http://..../web/content/347-fb4e346/web.assets_common.js:546:198
done@http://..../web/content/347-fb4e346/web.assets_common.js:937:86
callback@http://...../web/content/347-fb4e346/web.assets_common.js:957:15

Step to regenerate:
create new database with demo data
activate developer mode
install all hotel modules
On Reservation section,  click reservation summary, then the odoo client error is generated as above

expected behavior :  Not generating error  only message if there is no reservation yet

Please have a look

**Comment by JayVora-SerpentCS** [comment]
@bunhin Would you please try restarting server?

**Comment by JayVora-SerpentCS** [comment]
@KrishnaPrajapati-SerpentCS Please check.

**Comment by KrishnaPrajapati-SerpentCS** [comment]
Hello @bunhin 
I have installed all hotel management modules with demo data and I have not been able to capture any error.
Here you can see attached screenshot:
![reservation summary - odoo](https://user-images.githubusercontent.com/23502495/37591054-4338625e-2b90-11e8-8ad8-cda19243ecd1.png)

**Comment by JayVora-SerpentCS** [comment]
Are you using any 3rd party module @bunhin  ?

**Comment by JayVora-SerpentCS** [comment]
Closing for now

**Comment by bunhin** [comment]
I try to restart the server and there is no error now, i am sorry for delayed to response back.
