### ISSUE TITLE
API update: Yahoo finance API Discontinued 2017-11-06 

### ISSUE THREAD

**Issue by SmithLin0618** [OCA/vertical-hotel#39]
For Yahoo finance API Discontinued 2017-11-06
the currency exchange is not work now
 can you help to change the api to free.currencyconverterapi.com

A sample conversion URL is: http://free.currencyconverterapi.com/api/v5/convert?q=EUR_USD&compact=y

thank you

**Comment by JayVora-SerpentCS** [comment]
@SmithLin0618 we will surely keep this in plan. Thanks.

**Comment by JayVora-SerpentCS** [comment]
@darshan-serpent Please check that and do the needful.

**Comment by JayVora-SerpentCS** [comment]
We've achieved this under https://github.com/OCA/currency, so we dropped off static call of Exchange from Hotel since v11.
Thanks.
