### ISSUE TITLE
[11.0] invalid form view sequence in folio line room no and also different category

### ISSUE THREAD

**Issue by vimalpatelserpentcs** [OCA/vertical-hotel#51]
Steps :
Create New folio 
In  Room Lines click on **Add and item** 
Select Room No And open its view

![hotel-issue-03](https://user-images.githubusercontent.com/27808219/48965717-61610700-efe8-11e8-8869-63580e0b06f9.png)

![hotel-issue-01](https://user-images.githubusercontent.com/27808219/48965692-11824000-efe8-11e8-9df7-e0eae52e5bf0.png)

![hotel-issue-02](https://user-images.githubusercontent.com/27808219/48965703-2b238780-efe8-11e8-9ba2-5778148e2f56.png)

**Comment by JayVora-SerpentCS** [comment]
@vimalpatelserpentcs Did any of your PR fixed it ?
