### ISSUE TITLE
Reservation Summary  White

### ISSUE THREAD

**Issue by Mimbex** [OCA/vertical-hotel#53]
![image](https://user-images.githubusercontent.com/4836710/49333725-d953a200-f591-11e8-9647-98a91459f08b.png)

i can't view the reservations

**Comment by fanguloaa** [comment]
i have the same issue any ideas?

**Comment by droidosergioh** [comment]
Yes I have same issue. I see the v11 miss board_frontdesk module. I have installed it trying to converting somehow to v11 but it did not solve it... Any idea please?

**Comment by makeplerc** [comment]
same issue, anyhelp?

**Comment by rbetancor** [comment]
Same here, had someone got the v11 version to work?

**Comment by JayVora-SerpentCS** [comment]
@Nikul-Chaudhary @vimalpatelserpentcs Do check

**Comment by nikul-serpentcs** [comment]
> @Nikul-Chaudhary @vimalpatelserpentcs Do check

Sure @JayVora-SerpentCS

**Comment by nikul-serpentcs** [comment]
@Mimbex @fanguloaa @droidosergioh @makeplerc @rbetancor Could you please take a look with new Pull.

**Comment by Mimbex** [comment]
Works! fine now thanks!
