### ISSUE TITLE
Guest management should be One2Many with the Reservation, not One2One

### ISSUE THREAD

**Issue by rbetancor** [OCA/vertical-hotel#58]
In most countries, guest information should be transmited to the authorities, so should be better to handle that as a One2Many relation with the reservation and hotel folio, not One2One as now.

**Comment by Mimbex** [comment]
that's right i'm working in that customization :)

**Comment by Trivedi-Vacha-SerpentCS** [comment]
> that's right i'm working in that customization :)

@Mimbex Is it done?

**Comment by Mimbex** [comment]
@Trivedi-Vacha-SerpentCS  yes i forgot to release it
