### ISSUE TITLE
Version 12 only shows PDF Reports

### ISSUE THREAD

**Issue by jimdhope** [OCA/vertical-hotel#69]
I previously used Odoo 11 on a private server and this plugin worked great. I've just made a new installation of Odoo 12 on Azure and the plugin only shows a popup with options to generate a PDF Report. I recreated this on a separate private server installation of Odoo 12 too.

Any help would be greatly appreciated

**Comment by therealmjk** [comment]
@joycehuan pls can u help

**Comment by luistorresm** [comment]
Hello @jimdhope @therealmjk 

That repo is in progress for v12.

But maybe you need to add your user to the `Hotel Management / User - Manager` group to see the menus.

Could you test with that, please?

Regards

**Comment by therealmjk** [comment]
@luistorresm Yeah thanks i figured tht out. Its actually the user group problem
