### ISSUE TITLE
Pricelist is ignored

### ISSUE THREAD

**Issue by ramon-flashtec** [OCA/vertical-hotel#78]
When I configure pricelists for the rooms (in sales module), these are ignored in the hotel module and the normal price is used for the calculation. The lists work in the sales module. It would be nice to be able to deposit discounts for the amount of adults and children. 

For example:
1 adult: 40 € per person = 40 € total
2 adults: 25 € per person = 50 € total
3 adults 20 € per person = 60 € total

regards

**Comment by Fazryan** [comment]
I have the same issue,
Need help here.

**Comment by mclaeysb** [comment]
This was fixed by https://github.com/OCA/vertical-hotel/pull/117
