### ISSUE TITLE
How call the fields with php

### ISSUE THREAD

**Issue by CarlosTGodoy** [OCA/vertical-hotel#87]
How can I call the fields of the reservation model? I am working with the API through php and when calling the reservation fields it has two different objects (hotel.reservation and hotel_reservation.line, the latter is on the reservation line) and it does not allow me to call them in a single method.

**Comment by JayVora-SerpentCS** [comment]
@TorresGodoyCarlos 
You may look at the Official documentation : https://www.odoo.com/documentation/13.0/webservices/odoo.html
Thanks,
