### ISSUE TITLE
Timestamp on Booking

### ISSUE THREAD

**Issue by halonso1990** [OCA/vertical-hotel#89]
Hi team, I am new in odoo, I am installing the Hotel Management module, and everything is working, but my problem is whit timestamp, I've changed it on the server but the email templates still sending UTC time, I am needing this on CST, I've tried many ways but I am needing your experience to try to solve this, in worst case, do not display time on the email render
thank you so much

I am on odoo 12, ubuntu 18.04, community edition
Thanks

**Comment by kanys5** [comment]
Hi
Did you find a solution to this problem I have the same problem

**Comment by JayVora-SerpentCS** [comment]
@vimalpatelserpentcs can you check this please?
Thanks.

**Comment by JayVora-SerpentCS** [comment]
The linked PR fixed this.
